name: JaisonErick
favicon: null
layout_spectrum: 0.93643
typography_spectrum: 0.72638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a8e8'
    - '#ffffff'
    - '#000000'
    - '#b3e9f9'
    - '#005573'
  brandStrength: 0.5625
  lightness: 0.6052108102012426
  saturation: 0.4849835264030844
  rhythmicContrast: 0.1499091803561896
purpose: []
