name: JaisonErick
favicon: null
layout_spectrum: 0.3052845417987555
typography_spectrum: 0.21327072335407138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.6052108102012426
  saturation: 0.4849835264030844
  rhythmicContrast: 0.1499091803561896
purpose: []
